# Generated by Django 5.1.3 on 2024-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_about_contact_introduction_myservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='greet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
