# Generated by Django 5.1.3 on 2024-12-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_skill_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myservice',
            name='service_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
