# Generated by Django 5.1.3 on 2025-01-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_myservice_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='image',
            field=models.ImageField(blank=True, storage='api.storage.VercelBlobStorage', upload_to='images/'),
        ),
    ]
