# Generated by Django 5.1.3 on 2025-01-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_introduction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
