# Generated by Django 5.1.3 on 2025-01-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_introduction_blob_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='blob_url',
        ),
        migrations.AlterField(
            model_name='introduction',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
