# Generated by Django 5.1.3 on 2025-01-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_introduction_blob_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='myservice',
            name='service_image',
            field=models.ImageField(blank=True, upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, upload_to='skills_images/'),
        ),
    ]
