# Generated by Django 5.1.3 on 2025-01-13 19:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_about_image_alter_myservice_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
